### ISSUE TITLE
Create basic database for login & registration

### ISSUE THREAD

**Issue by siddesloth** [hnegus1/UWE-ESD-2018-Assignment#2]
The main database needs to be created to allow the login and registration functions to work

**Comment by hnegus1** [comment]
The database has been made enough that #3 and #4 can be started now!

You should be able to pull the project directly from Netbeans. [I have made a wiki page on how to do this if you are unsure.](https://github.com/hnegus1/UWE-ESD-2018-Assignment/wiki/Using-GitHub-with-Netbeans)

To make developing both of these issues easier, I have implemented a way of entering the SQL through servlets without having to set up a connection on every servlet. [More information can be found here.](https://github.com/hnegus1/UWE-ESD-2018-Assignment/wiki/Using-SQL-with-Servlets) There may be problems with this, so I will keep this issue open so people can let me know if they encounter any.

**Comment by hnegus1** [comment]
Task complete.
